//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.LoadUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoadUser.ILoadUser")]
    public interface ILoadUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadUser/LoadUser", ReplyAction="http://tempuri.org/ILoadUser/LoadUserResponse")]
        bool LoadUser(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadUser/LoadUser", ReplyAction="http://tempuri.org/ILoadUser/LoadUserResponse")]
        System.Threading.Tasks.Task<bool> LoadUserAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadUserChannel : WindowsFormsApp1.LoadUser.ILoadUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadUserClient : System.ServiceModel.ClientBase<WindowsFormsApp1.LoadUser.ILoadUser>, WindowsFormsApp1.LoadUser.ILoadUser {
        
        public LoadUserClient() {
        }
        
        public LoadUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LoadUser(string Id) {
            return base.Channel.LoadUser(Id);
        }
        
        public System.Threading.Tasks.Task<bool> LoadUserAsync(string Id) {
            return base.Channel.LoadUserAsync(Id);
        }
    }
}
